spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
            authorization-grant-type: authorization_code
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ${KAKAO_ADMIN_KEY}
            client-name: Kakao
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          writetimeout: 5000
      sender:
        email: ${SENDER_EMAIL}
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?

security:
  permit-all:
    - /
    - /api/auth/users/login
    - /error
    - /api/mail/verify-email
    - /api/token/refresh
  role-mappings:
    - roles: [USER, UNVERIFIED_USER]
      urls:
        - /api/users/random-nickname
        - /api/files/default-profile-image
        - /api/users/change-email
    - roles: [ADMIN]
      urls:
        - /api/admin/**
  default-role: USER

file:
  max-size: ${FILE_MAX_SIZE}
  image-extensions: ${FILE_IMAGE_EXT}
  uncompressed-extensions: ${FILE_UNCOMPRESSED_EXT}
  allowed-extensions: ${FILE_ALLOWED_EXT}
  upload-root: ${FILE_UPLOAD_PATH}
  default-image-detail-id: ${FILE_DEFAULT_IMAGE_DETAIL_ID}