spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: developer
    password: emrkwk0128!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
