name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:

    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      SPRING_PROFILES_ACTIVE: test
      DB_URL: localhost
      DB_PORT: 3306
      DB_NAME: ${{ secrets.MYSQL_DATABASE }}
      DB_USER: ${{ secrets.MYSQL_USER }}
      DB_PASS: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Gradle Build Cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/build-cache
          key: ${{ runner.os }}-gradle-build-cache
          restore-keys: |
            ${{ runner.os }}-gradle-build-cache

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 3306 && echo "MySQL is up" && exit 0
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL did not start in time" && exit 1

      - name: Run Tests with Coverage
        run: ./gradlew test jacocoTestReport --no-daemon

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build/logs/
